package controllers
package controllers

import (
	"context"
	"fmt"

	appsv1 "k8s.io/api/apps/v1"
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/util/intstr"
	ctrl "sigs.k8s.io/controller-runtime"
	"sigs.k8s.io/controller-runtime/pkg/client"
	"sigs.k8s.io/controller-runtime/pkg/controller/controllerutil"
	"sigs.k8s.io/controller-runtime/pkg/log"

	todolistv1 "todolist-operator/api/v1"
)

// TodoListReconciler reconciles a TodoList object
type TodoListReconciler struct {
	client.Client
	Scheme *runtime.Scheme
}

// +kubebuilder:rbac:groups=todolist.example.com,resources=todolists,verbs=get;list;watch;create;update;patch;delete
// +kubebuilder:rbac:groups=todolist.example.com,resources=todolists/status,verbs=get;update;patch
// +kubebuilder:rbac:groups=todolist.example.com,resources=todolists/finalizers,verbs=update
// +kubebuilder:rbac:groups=apps,resources=deployments,verbs=get;list;watch;create;update;patch;delete
// +kubebuilder:rbac:groups=core,resources=services,verbs=get;list;watch;create;update;patch;delete
// +kubebuilder:rbac:groups=core,resources=configmaps,verbs=get;list;watch;create;update;patch;delete
// +kubebuilder:rbac:groups=core,resources=secrets,verbs=get;list;watch;create;update;patch;delete

// Reconcile is part of the main kubernetes reconciliation loop
func (r *TodoListReconciler) Reconcile(ctx context.Context, req ctrl.Request) (ctrl.Result, error) {
	log := log.FromContext(ctx)

	// Fetch the TodoList instance
	todoList := &todolistv1.TodoList{}
	err := r.Get(ctx, req.NamespacedName, todoList)
	if err != nil {
		if errors.IsNotFound(err) {
			// Object not found, could have been deleted
			log.Info("TodoList resource not found. Ignoring since object must be deleted")
			return ctrl.Result{}, nil
		}
		log.Error(err, "Failed to get TodoList")
		return ctrl.Result{}, err








































































































































































































































































































































































































































































}		Complete(r)		Owns(&corev1.Secret{}).		Owns(&corev1.ConfigMap{}).		Owns(&corev1.Service{}).		Owns(&appsv1.Deployment{}).		For(&todolistv1.TodoList{}).	return ctrl.NewControllerManagedBy(mgr).func (r *TodoListReconciler) SetupWithManager(mgr ctrl.Manager) error {// SetupWithManager sets up the controller with the Manager.}	return err	}		return r.Create(ctx, service)	if err != nil && errors.IsNotFound(err) {	err = r.Get(ctx, client.ObjectKey{Name: service.Name, Namespace: service.Namespace}, foundSvc)	foundSvc := &corev1.Service{}	}		return err	if err := controllerutil.SetControllerReference(todoList, service, r.Scheme); err != nil {	}		},			Type: corev1.ServiceTypeClusterIP,			},				},					TargetPort: intstr.FromInt(8080),					Port:       8080,					Name:       "http",				{			Ports: []corev1.ServicePort{			},				"owner": owner,				"app":   "todolist-vue",			Selector: map[string]string{		Spec: corev1.ServiceSpec{		},			Namespace: todoList.Namespace,			Name:      fmt.Sprintf("%s-todolist-vue", owner),		ObjectMeta: metav1.ObjectMeta{	service := &corev1.Service{	// Frontend Service	}		}			return err		if err := r.Create(ctx, deployment); err != nil {	if err != nil && errors.IsNotFound(err) {	err := r.Get(ctx, client.ObjectKey{Name: deployment.Name, Namespace: deployment.Namespace}, found)	found := &appsv1.Deployment{}	}		return err	if err := controllerutil.SetControllerReference(todoList, deployment, r.Scheme); err != nil {	}		},			},				},					},						},							},								},									},										},											Name: fmt.Sprintf("%s-todolist-vue-config", owner),										LocalObjectReference: corev1.LocalObjectReference{									ConfigMapRef: &corev1.ConfigMapEnvSource{								{							EnvFrom: []corev1.EnvFromSource{							},								{ContainerPort: 8080},							Ports: []corev1.ContainerPort{							Image: "ghcr.io/bennyro-mta/todolist-vue:1.2",							Name:  "todolist-vue",						{					Containers: []corev1.Container{				Spec: corev1.PodSpec{				},					},						"owner": owner,						"app":   "todolist-vue",					Labels: map[string]string{				ObjectMeta: metav1.ObjectMeta{			Template: corev1.PodTemplateSpec{			},				},					"owner": owner,					"app":   "todolist-vue",				MatchLabels: map[string]string{			Selector: &metav1.LabelSelector{			Replicas: &replicas,		Spec: appsv1.DeploymentSpec{		},			Namespace: todoList.Namespace,			Name:      fmt.Sprintf("%s-todolist-vue", owner),		ObjectMeta: metav1.ObjectMeta{	deployment := &appsv1.Deployment{	replicas := int32(1)	// Frontend Deploymentfunc (r *TodoListReconciler) reconcileFrontend(ctx context.Context, todoList *todolistv1.TodoList, owner string) error {}	return err	}		return r.Create(ctx, service)	if err != nil && errors.IsNotFound(err) {	err = r.Get(ctx, client.ObjectKey{Name: service.Name, Namespace: service.Namespace}, foundSvc)	foundSvc := &corev1.Service{}	}		return err	if err := controllerutil.SetControllerReference(todoList, service, r.Scheme); err != nil {	}		},			Type: corev1.ServiceTypeClusterIP,			},				},					TargetPort: intstr.FromInt(8080),					Port:       8080,					Name:       "http",				{			Ports: []corev1.ServicePort{			},				"owner": owner,				"app":   "todo-api",			Selector: map[string]string{		Spec: corev1.ServiceSpec{		},			Namespace: todoList.Namespace,			Name:      fmt.Sprintf("%s-todo-api", owner),		ObjectMeta: metav1.ObjectMeta{	service := &corev1.Service{	// Todo API Service	}		}			return err		if err := r.Create(ctx, deployment); err != nil {	if err != nil && errors.IsNotFound(err) {	err := r.Get(ctx, client.ObjectKey{Name: deployment.Name, Namespace: deployment.Namespace}, found)	found := &appsv1.Deployment{}	}		return err	if err := controllerutil.SetControllerReference(todoList, deployment, r.Scheme); err != nil {	}		},			},				},					},						},							},								},									},										},											Key: "MYSQL_ROOT_PASSWORD",											},												Name: fmt.Sprintf("%s-todolist-secret", owner),											LocalObjectReference: corev1.LocalObjectReference{										SecretKeyRef: &corev1.SecretKeySelector{									ValueFrom: &corev1.EnvVarSource{									Name: "MYSQL_PASSWORD",								{							Env: []corev1.EnvVar{							},								},									},										},											Name: fmt.Sprintf("%s-todolist-config", owner),										LocalObjectReference: corev1.LocalObjectReference{									ConfigMapRef: &corev1.ConfigMapEnvSource{								{							EnvFrom: []corev1.EnvFromSource{							},								{ContainerPort: 8080, Name: "http"},							Ports: []corev1.ContainerPort{							Image: "ghcr.io/bennyro-mta/todos-api:1.2",							Name:  "todo-api",						{					Containers: []corev1.Container{				Spec: corev1.PodSpec{				},					},						"owner": owner,						"app":   "todo-api",					Labels: map[string]string{				ObjectMeta: metav1.ObjectMeta{			Template: corev1.PodTemplateSpec{			},				},					"owner": owner,					"app":   "todo-api",				MatchLabels: map[string]string{			Selector: &metav1.LabelSelector{			Replicas: &replicas,		Spec: appsv1.DeploymentSpec{		},			Namespace: todoList.Namespace,			Name:      fmt.Sprintf("%s-todo-api", owner),		ObjectMeta: metav1.ObjectMeta{	deployment := &appsv1.Deployment{	replicas := int32(1)	// Todo API Deploymentfunc (r *TodoListReconciler) reconcileTodoAPI(ctx context.Context, todoList *todolistv1.TodoList, owner string) error {}	return err	}		return r.Create(ctx, service)	if err != nil && errors.IsNotFound(err) {	err = r.Get(ctx, client.ObjectKey{Name: service.Name, Namespace: service.Namespace}, foundSvc)	foundSvc := &corev1.Service{}	}		return err	if err := controllerutil.SetControllerReference(todoList, service, r.Scheme); err != nil {	}		},			Type: corev1.ServiceTypeClusterIP,			},				},					TargetPort: intstr.FromInt(3306),					Port:       3306,				{			Ports: []corev1.ServicePort{			},				"owner": owner,				"app":   "mariadb",			Selector: map[string]string{		Spec: corev1.ServiceSpec{		},			Namespace: todoList.Namespace,			Name:      fmt.Sprintf("%s-mariadb", owner),		ObjectMeta: metav1.ObjectMeta{	service := &corev1.Service{	// MariaDB Service	}		}			return err		if err := r.Create(ctx, deployment); err != nil {	if err != nil && errors.IsNotFound(err) {	err := r.Get(ctx, client.ObjectKey{Name: deployment.Name, Namespace: deployment.Namespace}, found)	found := &appsv1.Deployment{}	}		return err	if err := controllerutil.SetControllerReference(todoList, deployment, r.Scheme); err != nil {	}		},			},				},					},						},							},								EmptyDir: &corev1.EmptyDirVolumeSource{},							VolumeSource: corev1.VolumeSource{							Name: "mariadb-data",						{					Volumes: []corev1.Volume{					},						},							},								},									MountPath: "/var/lib/mysql",									Name:      "mariadb-data",								{							VolumeMounts: []corev1.VolumeMount{							},								},									},										},											Key: "MYSQL_ROOT_PASSWORD",											},												Name: fmt.Sprintf("%s-todolist-secret", owner),											LocalObjectReference: corev1.LocalObjectReference{										SecretKeyRef: &corev1.SecretKeySelector{									ValueFrom: &corev1.EnvVarSource{									Name: "MYSQL_ROOT_PASSWORD",								{							Env: []corev1.EnvVar{							},								{ContainerPort: 3306},							Ports: []corev1.ContainerPort{							Image: "mariadb:latest",							Name:  "mariadb",						{					Containers: []corev1.Container{				Spec: corev1.PodSpec{				},					},						"owner": owner,						"app":   "mariadb",					Labels: map[string]string{				ObjectMeta: metav1.ObjectMeta{			Template: corev1.PodTemplateSpec{			},				},					"owner": owner,					"app":   "mariadb",				MatchLabels: map[string]string{			Selector: &metav1.LabelSelector{			Replicas: &replicas,		Spec: appsv1.DeploymentSpec{		},			Namespace: todoList.Namespace,			Name:      fmt.Sprintf("%s-mariadb", owner),		ObjectMeta: metav1.ObjectMeta{	deployment := &appsv1.Deployment{	replicas := int32(1)	// MariaDB Deploymentfunc (r *TodoListReconciler) reconcileMariaDB(ctx context.Context, todoList *todolistv1.TodoList, owner string) error {}	return err	}		return r.Create(ctx, frontendConfigMap)	if err != nil && errors.IsNotFound(err) {	err = r.Get(ctx, client.ObjectKey{Name: frontendConfigMap.Name, Namespace: frontendConfigMap.Namespace}, found)	}		return err	if err := controllerutil.SetControllerReference(todoList, frontendConfigMap, r.Scheme); err != nil {	}		},			"USER":         owner,			"API_BASE_URL": "/todos",		Data: map[string]string{		},			Namespace: todoList.Namespace,			Name:      fmt.Sprintf("%s-todolist-vue-config", owner),		ObjectMeta: metav1.ObjectMeta{	frontendConfigMap := &corev1.ConfigMap{	// ConfigMap for frontend	}		}			return err		if err := r.Create(ctx, apiConfigMap); err != nil {	if err != nil && errors.IsNotFound(err) {	err := r.Get(ctx, client.ObjectKey{Name: apiConfigMap.Name, Namespace: apiConfigMap.Namespace}, found)	found := &corev1.ConfigMap{}	}		return err	if err := controllerutil.SetControllerReference(todoList, apiConfigMap, r.Scheme); err != nil {	}		},			"MYSQL_TABLE": "todos",			"MYSQL_USER":  "root",			"MYSQL_HOST":  fmt.Sprintf("%s-mariadb", owner),			"MYSQL_DB":    "todolist",		Data: map[string]string{		},			Namespace: todoList.Namespace,			Name:      fmt.Sprintf("%s-todolist-config", owner),		ObjectMeta: metav1.ObjectMeta{	apiConfigMap := &corev1.ConfigMap{	// ConfigMap for todo-apifunc (r *TodoListReconciler) reconcileConfigMaps(ctx context.Context, todoList *todolistv1.TodoList, owner string) error {}	return err	}		return r.Create(ctx, secret)	if err != nil && errors.IsNotFound(err) {	err := r.Get(ctx, client.ObjectKey{Name: secret.Name, Namespace: secret.Namespace}, found)	found := &corev1.Secret{}	}		return err	if err := controllerutil.SetControllerReference(todoList, secret, r.Scheme); err != nil {	}		},			"MYSQL_ROOT_PASSWORD": []byte("todolist123"),		Data: map[string][]byte{		Type: corev1.SecretTypeOpaque,		},			Namespace: todoList.Namespace,			Name:      fmt.Sprintf("%s-todolist-secret", owner),		ObjectMeta: metav1.ObjectMeta{	secret := &corev1.Secret{func (r *TodoListReconciler) reconcileSecret(ctx context.Context, todoList *todolistv1.TodoList, owner string) error {}	return ctrl.Result{}, nil	log.Info("Successfully reconciled TodoList", "owner", owner)	}		return ctrl.Result{}, err		log.Error(err, "Failed to update TodoList status to Running")	if err := r.Status().Update(ctx, todoList); err != nil {	todoList.Status.FrontendReady = true	todoList.Status.TodoAPIReady = true	todoList.Status.MariaDBReady = true	todoList.Status.Phase = "Running"	// Update status to Running	}		return ctrl.Result{}, err		log.Error(err, "Failed to reconcile Frontend")	if err := r.reconcileFrontend(ctx, todoList, owner); err != nil {	// Create Frontend Deployment and Service	}		return ctrl.Result{}, err		log.Error(err, "Failed to reconcile Todo API")	if err := r.reconcileTodoAPI(ctx, todoList, owner); err != nil {	// Create Todo API Deployment and Service	}		return ctrl.Result{}, err		log.Error(err, "Failed to reconcile MariaDB")	if err := r.reconcileMariaDB(ctx, todoList, owner); err != nil {	// Create MariaDB Deployment and Service	}		return ctrl.Result{}, err		log.Error(err, "Failed to reconcile ConfigMaps")	if err := r.reconcileConfigMaps(ctx, todoList, owner); err != nil {	// Create ConfigMaps	}		return ctrl.Result{}, err		log.Error(err, "Failed to reconcile Secret")	if err := r.reconcileSecret(ctx, todoList, owner); err != nil {	// Create Secret	owner := todoList.Spec.Owner	}		}			return ctrl.Result{}, err			log.Error(err, "Failed to update TodoList status")		if err := r.Status().Update(ctx, todoList); err != nil {		todoList.Status.Phase = "Pending"	if todoList.Status.Phase == "" {	// Set initial status	}		return ctrl.Result{}, nil		log.Info("TodoList is immutable after deployment", "phase", todoList.Status.Phase)	if todoList.Status.Phase != "" && todoList.Status.Phase != "Pending" {	// Check if immutable after creation	}