apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- todolist-crd.yaml
- todo-crd.yaml
- operator.yaml
- rbac.yaml

images:
- name: todolist-operator
  newName: todolist-operator
  newTag: latest

namespace: todolist-operator-system
