apiVersion: todolist.example.com/v1
kind: TodoList
metadata:
  name: benny-todolist
  namespace: default
spec:
  owner: benny
  frontendReplicas: 1
  apiReplicas: 1
  serviceType: LoadBalancer
  apiBaseUrl: /todos
